[package]
name = "wei-daemon"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wei-log = "0.2.0"
tokio = { version = "1.28.1", features = ["full"] }
winapi = { version = "0.3.9", features = ["winuser", "wincon"] }
sysinfo = "0.29.0"
single-instance = "0.3"
dirs = "5.0.1"