[package]
name = "wei-daemon"
version = "0.2.0"
edition = "2021"
description = "wei daemon"
documentation = "https://github.com/zuiyue-com/wei-daemon"
homepage = "https://github.com/zuiyue-com/wei-daemon"
license = "MIT OR Apache-2.0"


[dependencies]
wei-log = "0.2.0"
tokio = { version = "1.28.1", features = ["full"] }
winapi = { version = "0.3.9", features = ["winuser", "wincon"] }
sysinfo = "0.29.0"
single-instance = "0.3"
dirs = "5.0.1"